---
title: "Draft R Markdown document"
author: "Your Name"
output: html_document
editor_options:
  markdown:
    wrap: 72
    canonical: true
---

```{r setup, include=FALSE}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
lipidomics <- targets::tar_read(lipidomics)
source(here::here("R/functions.R"))
```

## Basic statistics

```{r}
descriptive_stats(lipidomics)
```

## Figures

```{r}
gender_by_class_plot <- lipidomics %>%
  distinct(code, gender, class) %>%
  ggplot(aes(x = class, fill = gender)) +
  geom_bar(position = "dodge")
gender_by_class_plot
```

```{r}
metabolite_distribution_plot <- ggplot(lipidomics, aes(x = value)) +
  geom_histogram() +
  facet_wrap(vars(metabolite), scales = "free")
metabolite_distribution_plot
```

## Building the model

```{r}
log_reg_specs <- logistic_reg() %>%
  set_engine("glm")
log_reg_specs
```

## Exercise 7.5

### Linear regression model definition

```{r}
linear_reg_specs <- linear_reg() %>% 
  set_engine("lm")
linear_reg_specs
```

## Inspect data, need to wrangle data a bit pre-modeling

```{r}
lipidomics %>% 
  count(code, metabolite) %>% 
  filter(n > 1)
```

## Use curly curly to apply snakecase to columns of our choice, not just metabolite #nolint

```{r}
column_values_to_snakecase <- function(data, cols) {
  data %>%
    dplyr::mutate(dplyr::across({{ cols }}, snakecase::to_snake_case))
}

lipidomics %>%
  column_values_to_snakecase(metabolite)
```

## Mutate the data, create function for pivot wider

```{r}
lipidomics_wide <- lipidomics %>%
  mutate(metabolite = snakecase::to_snake_case(metabolite)) %>%
  pivot_wider(
    names_from = metabolite, 
    values_from = value, 
    values_fn = mean,
    names_prefix = "metabolite_"
  )
lipidomics_wide
```

## Transforming data

```{r}
  recipes::recipe(data) %>% 
  recipes::update_role({{metabolite_variable}}, age, gender, new_role = "predictors") %>% 
  recipes::update_role(class, new_role = "outcome") %>% 
  recipes::step_normalize(tidyselect::starts_with("metabolite_"))
```
