---
title: "Analysis of lipidomics dataset"
format: html
author: 
  - name: Daniel T. Cervone
    orcid: 0000-0001-5675-4985
    email: daniel.cervone@gmail.com
    affiliations: 
      - name: Novo Nordisk Foundation CBMR
        address: Blegdamsvej 3B
        city: København S
        postal-code: 2300
---

```{r setup, include=FALSE}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
lipidomics <- targets::tar_read(lipidomics)

```

# Abstract

Objective:

Research Design and Methods:

Results:

Conclusions:

# Introduction 

# Research Design and Methods

# Results
```{r echo = FALSE}
tar_read(df_stats_by_metabolite) %>% 
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>% 
  knitr::kable(caption = "Descriptive statistics of metabolites.")
```

```{r echo = FALSE}
tar_read(fig_gender_by_class)
```

```{r echo = FALSE}
tar_read(fig_metabolite_distribution)
```

```{r echo = FALSE}
tar_read(fig_model_estimates)
```

# Conclusions

# Acknowledgements

# References

# Tables

# Figures

# Supplemental Material
